export const PHRASES = [
  "O segredo é ter fé em Deus.",
  "O Criador de todas as coisas mora em mim.",
  "Não deixe o mundo te separar do amor de Deus.",
  "Deus está comigo.",
  "Ore. Espere. Confie.",
  "A mão de Deus vai escrever mais um de seus milagres.",
  "Amar a Deus sobre todas as coisas.",
  "Eu sei que tudo que Deus faz durará eternamente.",
  "Coloque Deus no início que ele cuidará do fim.",
  "Livrai-me de todo o mal. Amém!",
  "O mundo fecha portas, mas Deus abre caminhos.",
  "Jesus é o meu capitão e minha alma nele confia.",
  "Ele morreu para nos provar o seu amor.",
  "O tempo de Deus é perfeito.",
  "A fé em Deus nos faz crer no incrível, ver o invisível e realizar o impossível.",
  "Talvez Deus não mude tua situação, mas Ele está usando essa situação para mudar você.",
  "Obrigado, Deus, por não fazer as minhas vontades, mas sim atender as minhas necessidades.",
  "Entregue o seu caminho ao Senhor; confie nele, e ele agirá.",
  "Não perca a fé. As coisas vão acontecer no momento certo, basta você saber esperar.",
  "Enquanto Deus for meu chão, não há quem me derrube.",
  "A fonte do amor e da verdade tem um só nome: Deus.",
  "Acredite com muita fé no que você quer e automaticamente tudo se tornará possível.",
  "A busca de Deus é a busca da alegria. O encontro com Deus é a própria alegria.",
  "Não adianta agradar a todos e desagradar a Deus.",
  "Quanto mais você enche seu coração de Deus, menos apertado ele fica.",
  "Em qualquer tempo em que eu temer, confiarei em ti.",
  "Deus tira o que te fere pra te dar o que te cura!",
  "Ele é o caminho, a verdade e a vida.",
  "Aquele que não ama não conhece a Deus; porque Deus é amor.",
  "O amor é o dom divino. É o próprio Deus se revelando. O amor tudo refaz. Se algo nos falta, o amor nos traz. Tudo é completo com amor.",
  "Porque onde tem amor, tem cheirinho de paz, tem gostinho de Deus.",
  "Deus, mesmo quando tudo for dor, me ensine a ser amor.",
  "Onde há fé, há amor. Onde há amor, há paz. Onde há paz, há Deus. Onde há Deus, nada falta.",
  "Cristo ensinou que é preciso amar ao Senhor sobre todas as coisas e ao próximo como a si mesmo.",
  "O Senhor vive no coração de quem ama.",
  "O mundo nos ensina a criticar e a julgar as pessoas. Deus nos ensina a amá-las e a orar por elas.",
  "Deus cuida de mim, porque ele é a essência do amor e esse é o sentimento que mais preciso na minha vida.",
  "O amor de Deus não muda, não falha e dura para sempre!",
  "Amar e ajudar o próximo é servir a Deus e usar a Sua palavra para tornar este mundo melhor.",
  "Que Deus esteja sempre com você, mas acima de tudo, que você esteja sempre com Deus. Boa noite!",
  "Que possamos encarar e compreender a vida com mais sabedoria e menos desespero, mais paciência e menos revolta. Que sejamos rodeados com os anjos de Deus e inspirados apenas pelo bem. Boa noite!",
  "Que Deus nos dê força, fortaleça nossa fé, nos blinde com sua proteção, faça a noite ser leve e o dia amanhecer lindo, luminoso e cheio de motivos para sermos ainda mais felizes. Boa noite!",
  "Que Deus abençoe nossa noite e nos prepare um lindo amanhecer. Boa noite!",
  "Antes de dormir entregue toda a sua ansiedade a Deus e esqueça-a. Deus está sempre trabalhando por você. Boa noite!",
  "Boa noite. Confie em Deus, Ele é poderoso para fazer infinitamente mais do que pensamos e pedimos.",
  "Nada melhor do que um dia após o outro e Deus à frente de tudo. Boa noite!",
  "Que Deus esteja sempre com você e sua família, abençoando e protegendo o seu lar. Boa noite!",
  "Não importa se o mundo está contra você, faça de Deus a sua força para vencer. Boa noite!",
  "Que Deus proteja o seu sono e jogue fora tudo de ruim que passou. Boa noite!",
  "Boa noite! Que Deus ilumine o seu caminho e os seus sonhos, e traga um novo dia com tudo de melhor que existe.",
  "Grandioso é o Senhor e grande são os planos dEle para a sua vida. Boa noite!",
  "Abençoado por Deus.",
  "A fé me move.",
  "Em teus braços é o meu descanso.",
  "Entrego, confio, aceito e agradeço.",
  "Jesus Cristo, minha vida.",
  "O meu Deus é o Deus do impossível.",
  "O Senhor me fortalece.",
  "A cruz sagrada seja a minha luz.",
  "Sempre me rege, me guarde, me ilumine. Amém.",
  "Eu não ando só.",
  "Tua graça me basta.",
  "O meu Deus nunca falhará.",
  "Tudo no tempo de Deus.",
  "Ele está em todas as coisas.",
  "Ele não desiste de você.",
  "Nunca foi sorte, sempre foi Deus.",
  "Eu confio Nele.",
  "Nada supera o amor de Deus.",
  "Floresça onde Deus te plantar.",
  "Cristo vive em mim.",
  "Deus está no controle de tudo.",
  "Talvez Deus não mude tua situação, mas Ele está usando essa situação para mudar você.",
  "Querido Deus, graças Te dou por me ouvir, me guardar e por fazer de tudo para me ver sorrir! (Salmo 64)",
  "Enquanto há vida, há esperança. (Eclesiastes 9:4)",
  "Deus transforma choro em sorriso, dor em força, fraqueza em fé e sonho em realidade.",
  "A fé em Deus nos faz crer no incrível, ver o invisível e realizar o impossível.",
  "Querido Deus, Tu és minha proteção, a minha fortaleza. Tu és o meu Deus, eu confio em Ti. (Salmo 91:2)",
  "Não sei o que me espera amanhã, mas estou em paz, pois sei que Deus tem o melhor para mim.",
  "Ensina-me, Senhor, o Teu caminho, e andarei na Tua verdade; une o meu coração ao temor do Teu nome. (Salmo 86:11)",
  "Se Deus encheu tua vida de obstáculos, é porque ele acredita na tua capacidade de passar por cada um.",
  "Eu quero dedicar a Jesus cada batida do meu coração, porque foi por mim que o seu coração parou de bater.",
  "Das alturas, o Eterno enxerga as profundezas. Não importa a distância, Ele sabe tudo sobre nós. (Salmo 138:6)",
  "Senhor, dê-me serenidade para aceitar as coisas que não posso modificar, coragem para modificar as que posso, e sabedoria para reconhecer a diferença entre elas.",
  "Querido Deus, ajuda-me a ser sábio e disposto a Te obedecer.",
  "Eu sou o caminho, e a verdade e a vida: ninguém vem ao Pai, senão por mim. (João 14:6)",
  "Querido Deus, em tuas mãos, coloco minhas preocupações, cuidados e problemas. Em tua sabedoria, coloco meu caminho, minhas direções e meus objetivos. Em teu amor, coloco minha vida!",
  "Ninguém vai me amar do jeito que Jesus me ama.",
  "Senhor a Ti clamo, escuta-me; inclina os Teus ouvidos à minha voz, quando a Ti clamar. (Salmo 141:1)",
  "Uma grande história é feita de grandes desafios que são conquistados com grandes esforços, formados de grandes sonhos e vindos de um grande Deus.",
  "Prepare-se! O dia do Senhor está perto.",
  "Jesus é único e incomparável. Não há ninguém igual a Ele.",
  "Jesus é tudo pra mim!",
  "Descanse o seu coração sobre a fidelidade de Deus, Ele nunca falha.",
  "Senhor, me faça forte pra poder continuar, não me deixe fraquejar. Me guie onde eu for, me livre do perigo, do meu caminho afaste o inimigo.",
  "Deus não faz nada antes, nem depois, Ele age na hora certa!",
  "É lindo saber que tem um Deus que cuida da gente.",
  "Venham e vejam o que Deus tem feito; como são impressionantes as suas obras em favor dos homens! (Salmos 66:5)",
  "Que nos falte tudo menos a presença de Deus.",
  "Deus te abençoe!",
  "Ninguém derruba a quem Deus levanta. Ninguém derrota a quem Deus protege. Ninguém amaldiçoa a quem Deus decide abençoar.",
  "Deus tem um propósito até nos dias mais difíceis.",
  "Vem! Vamos andar na luz do Senhor.(Isaías 2:5)",
  "Deus não castiga, Deus ensina. Deus não tira, Deus livra. Deus não demora, Deus capricha.",
  "Jesus é o amor da minha vida!",
  "4 Letras e 1 perfeição: Deus.",
  "Amigo de verdade é Deus.",
  "O único rei pra mim, usou coroa de espinhos: Jesus.",
  "Eu falo com Deus e sei que ele me ouve!",
  "Que a vida me traga coisas boas, mas sobretudo, que Deus me dê uma alma que nunca perde a fé!",
  "Eu sei que Deus está cuidando de cada detalhe!",
  "Deus, eu sei que Tu tens planos para a minha vida, não permita que eu me desvie deles.",
  "De todas as coisas a serem feitas antes de dormir, a melhor e mais certa é entregar tua vida e teu destino nas mãos de Deus.",
  "E seja sempre como Deus quiser.",
  "Querido Deus, me ajude a entender que é sua vontade, não a minha, que deve prevalecer. Que é no seu tempo, não no meu.",
  "Toda prece floresce!",
  "Muito mais do que você perdeu é o que Deus tem preparado para você.",
  "Quando Deus abre uma porta, ninguém pode fechar.",
  "Coloque nas mãos de Deus suas aflições e agradeça pelas suas vitórias.",
  "Deus faz tudo novo, de uma forma tão maravilhosa que você nem se lembra como era antes. (Isaías 65:17)",
  "Sorria! Deus te ama.",
  "Ele nunca vai te apontar o dedo e acusar, Ele vai te abraçar e perdoar.",
  "Sonho com o dia em que o sol de Deus vai espalhar justiça pelo mundo todo.",
  "Quando espero Tua voz estrondar, Tu vens com o silêncio."
]

export default {
    getTodaySPhrase: () => {
        const day = parseInt(+new Date() / (1000 * 60 * 60 * 24))
        return PHRASES[day % PHRASES.length]
    }
}